# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myxiangmu', '0004_auto_20181212_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
