# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myxiangmu', '0007_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='blog',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
